React 18: Typescript
thenativeweb/techlounge-react pull request #21
Opened 2021-01-14 12:47 UTC by davelosert

@goloroden : Hier der Code für Folge 18 und ggf. 19.

Nicht wundern: Ich habe die `eslintrc.json` in Folge 16 noch so angepasst, dass man mit dem Code die Installation / das Upgrade von TypeScript vornehmen kann ohne Fehler zu erhalten.

2021-01-14 18:26 UTC, goloroden requested changes

2021-01-14 18:26 UTC, goloroden commented on 18-typescript/package.json
> +  "description": "Der Einkaufslistenrechner aus Folge 16 - und bereit zur Nutzung von TypeScript!",
Name und Description passen noch nicht. Kannst Du da noch mal gucken?

2021-01-15 11:58 UTC, davelosert commented on 18-typescript/package.json
> +  "description": "Der Einkaufslistenrechner aus Folge 16 - und bereit zur Nutzung von TypeScript!",
Habs angepasst.

2021-01-15 17:38 UTC, goloroden approved these changes

2021-01-15 17:38 UTC, merged