React 26 Test Hooks And Fetch
thenativeweb/techlounge-react pull request #52
Opened 2021-09-30 16:22 UTC by davelosert

- chore: Copied code fomr episode 24 to 26
- feat: Adds asynchronous tests

2021-09-30 16:22 UTC, davelosert commented
@goloroden : hier der Code für die nächste Folge! :)

2021-09-30 19:07 UTC, goloroden requested changes
Hey @davelosert 👋 

It looks pretty good, there's only one minor catch. Can you please adjust this?

2021-09-30 19:07 UTC, goloroden commented on 26-test-hooks/package.json
> +  "description": "Wir schreiben Komponenten-Tests mit der React-Testing-Library und User-Event.",
Das ist noch der alte Text, oder?

2021-10-01 06:24 UTC, davelosert commented on 26-test-hooks/package.json
> +  "description": "Wir schreiben Komponenten-Tests mit der React-Testing-Library und User-Event.",
Good catch! :) 
Habs geändert.

2021-10-01 06:28 UTC, goloroden approved these changes

2021-10-01 06:28 UTC, merged