React 29: Adds code for custom hooks
thenativeweb/techlounge-react pull request #56
Opened 2021-11-01 13:53 UTC by davelosert

@goloroden : Hier der code für Folge 29

2021-11-01 15:58 UTC, goloroden approved these changes

2021-11-01 15:59 UTC, goloroden requested changes

2021-11-01 15:59 UTC, goloroden commented on 29-custom-hooks/package.json
> +  "description": "Wir schreiben Browser-Tests mit Cypress und Puppeteer.",
Müsste das nicht auf die Folge 29 angepasst sein?

2021-11-02 07:34 UTC, davelosert commented on 29-custom-hooks/package.json
> +  "description": "Wir schreiben Browser-Tests mit Cypress und Puppeteer.",
Ist angepasst

2021-11-02 07:34 UTC, davelosert commented
@goloroden : code für die Folge 30 hab ich auch noch direkt hinzugefügt.

2021-11-02 12:18 UTC, goloroden requested changes

2021-11-02 12:18 UTC, goloroden commented on 30-use-context/package.json
> +  "description": "Wir implementieren einen Custom-Hook.",
Now here 😉

2021-11-06 11:07 UTC, davelosert commented on 30-use-context/package.json
> +  "description": "Wir implementieren einen Custom-Hook.",
fixed :)

2021-11-06 11:16 UTC, goloroden approved these changes

2021-11-06 11:16 UTC, merged