React 09: shopping list
thenativeweb/techlounge-react pull request #9
Opened 2020-09-25 07:43 UTC by davelosert

Hi @goloroden ,

hier der Code für die nächste Folge.
Das ist doch einiges geworden - ich werde mal schauen, ob ich tatsächlich alles davon im Video programmiere oder da nicht etwas vorbereite. Bin außerdem gespannt, ob ich es auf einen Schlag hinbekomme 😅 

Freue mich auf dein Feedback.

2020-09-25 07:44 UTC, davelosert commented
Ach eine Frage habe ich da tatsächlich:
Die Lint Regeln besagen, dass bei verketten Funktionsaufrufen der Punkt jeweils am Ende der Zeile steht, also z.B.:

```javascript
[].
reduce(...).
reduce(..)
```

Ist das gewollt so? Frage nur, weil ich persönlich den Punkt am Anfang lesbarer finde.

2020-09-26 10:29 UTC, goloroden commented
Ja, das ist gewollt so.

Hintergrund ist, dass es die Lesbarkeit bei der Einrückung besser macht. Bei

```javascript
foo().
  bar();
```

siehst Du sofort, dass `bar` mit zwei Leerzeichen eingerückt ist. Bei

```javascript
foo()
  .bar();
```

lässt sich das nicht ganz so sicher sagen, weil der Punkt so unscheinbar ist, und man auf den ersten Blick auch meinen könnte, dass es drei Leerstellen sind. Deshalb haben wir uns vor geraumer Zeit für die erste Variante entschieden.

2020-09-26 10:36 UTC, goloroden requested changes
Hi @davelosert 👋 

Vielen Dank für die Anwendung, schaut sehr gut aus 😊 

Eigentlich gibt's nur eine einzige Kleinigkeit, die sich allerdings durch etliche Dateien zieht, deshalb habe ich das jetzt nicht im Online-Editor geändert:

`Ingredient` hast Du generell als `Ingridient` geschrieben (also mit `i` statt mit `e`). Du hast es aber wenigstens konsequent falsch geschrieben 😉 

Magst Du das im Code und in den Dateinamen noch ändern? Danach könnten wir mergen 😊

2020-09-27 08:11 UTC, davelosert commented
Ohje 🙈 - irgendwie dachte ich auch, man schreibt es so. 
Danke für den Hinweis und die kleinen Verbesserungen.

Hab die `ingredients` jetzt auch richtig benannt! :)

2020-09-29 19:10 UTC, goloroden approved these changes

2020-09-29 19:10 UTC, merged